### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Apofeozzz** [Clarifai/clarifai-apple-sdk#12]
ignoring file /Users/.../Desktop/ClarifiaTest/Pods/Clarifai-Apple-SDK/Clarifai_Apple_SDK.framework/Clarifai_Apple_SDK, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (arm64): /Users/.../Desktop/ClarifiaTest/Pods/Clarifai-Apple-SDK/Clarifai_Apple_SDK.framework/Clarifai_Apple_SDK

**Comment by dcirne** [comment]
Hi @Apofeozzz it seems that you are missing Git-LFS, as per instructions in the README (https://github.com/Clarifai/clarifai-apple-sdk#git-lfs). Please install Git-LFS are reinstall the Clarifai SDK. Things should just work after that.
