### ISSUE TITLE
Update notification names 

### ISSUE THREAD

**Issue by jlnbuiles** [Clarifai/clarifai-apple-sdk#13]
It seems like you updated the naming on your 3 model availability notifications without updating your readme. Shouldn't they be these:

`NSNotification.Name.CAIWillFetchModel` 
`NSNotification.Name.CAIDidFetchModel` 
`NSNotification.Name.CAIModelDidBecomeAvailable`

Or the shortened versions:
`.CAIWillFetchModel` 
`.CAIDidFetchModel` 
`.CAIModelDidBecomeAvailable`

**Comment by dcirne** [comment]
Hi @jlnbuiles,

Thanks for the heads up.

Those notifications have been marked as deprecated and the respective warning messages indicate which notifications they were replaced with. We will check the documentation and update.

**Comment by dcirne** [comment]
@jlnbuiles the notifications should work either or. Fully qualified name or shortened.
