### ISSUE TITLE
Concept IDs return names

### ISSUE THREAD

**Issue by jlnbuiles** [Clarifai/clarifai-apple-sdk#14]
While using the prediction API on your iOS SDK I'm getting all the `concept` `names` returned as `id`s. As I can see [here](https://clarifai.com/developer/guide/predict#predict) the `id attribute should return an actual identifier in the form of "ai_6kTjGfF6", but instead i'm getting things like "car", "transportation" and so on.

Here's a small code snippet i'm using on swift:

```

model?.predict(inputs, completionHandler: { (outputs, error) in
            if let results = outputs {
                for (index, output) in results.enumerated() {
                    
                    print("actual concept names: \(String(describing: results[index].dataAsset.concepts?.map({ $0.name })))\n")
                    print("actual concept IDs: \(String(describing: results[index].dataAsset.concepts?.map({ $0.id })))\n")
                    print("=========\n")
                }
            }
        })

```

for this code I'm getting the following logs:

actual concept names: Optional([Optional("people"), Optional("one"), Optional("adult"), Optional("man"), Optional("industry"), Optional("woman"), Optional("food"), Optional("business"), Optional("production"), Optional("hand"), Optional("vehicle"), Optional("recreation"), Optional("offense"), Optional("science"), Optional("chef"), Optional("skill"), Optional("education"), Optional("action"), Optional("indoors"), Optional("portrait")])

actual concept IDs: Optional(["people", "one", "adult", "man", "industry", "woman", "food", "business", "production", "hand", "vehicle", "recreation", "offense", "science", "chef", "skill", "education", "action", "indoors", "portrait"])

=========

**Comment by dcirne** [comment]
@jlnbuiles thanks for reporting the issue with the SDK. We heard you and have just released an updated version of the SDK (3.0.0-beta14) containing the fix.
