### ISSUE TITLE
auth refresh denied

### ISSUE THREAD

**Issue by sean808080** [Clarifai/clarifai-apple-sdk#16]
Not sure why I"m seeing this:
Clarifai:: SDK authentication refresh denied.

**Comment by dcirne** [comment]
@sean808080 the SDK needs to authenticate against the Clarifai cloud. For that it needs a valid API Key. You can create one for free at developer.clarifai.com.

**Comment by itsallmememe** [comment]
I'm getting the same issue. I've started a new project, it works ok on the web, but as soon as I try to use the iOS SDK it gives the following errors.

```Clarifai:: The SDK has been denied authentication.
Clarifai:: The SDK has not been initialized.
[logging] near "serialized_data": syntax error
📕 Clarifai:: Failed to open zip file```

**Comment by itsallmememe** [comment]
I've tried creating a new API key, but it doesn't make any difference.

**Comment by calee14** [comment]
I have this same error

**Comment by hengel2810** [comment]
I have the same problem, did anyone found a solution for this ?
