### ISSUE TITLE
Cant' depoly to device

### ISSUE THREAD

**Issue by schoes** [Clarifai/clarifai-apple-sdk#17]
Dear Clarifi 
I would like to test if the mobile SDK ist working on a device and always get the followign error/warning:
```/Users/svenschoeni/development/schatzmAIster/Clarifai/Clarifai_Apple_SDK.framework/Clarifai_Apple_SDK, missing required architecture arm64 in file /Users/svenschoeni/development/schatzmAIster/Clarifai/Clarifai_Apple_SDK.framework/Clarifai_Apple_SDK (1 slices)```
```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_Clarifai", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)```

Can you help me with this error ?

**Comment by dcirne** [comment]
Hi @schoes 

It seems you're almost there. Do you have Git LFS installed on your system? If not, please install and follow the installation instructions again (https://github.com/Clarifai/clarifai-apple-sdk#git-lfs)

Git LFS is used to download the library inside the SDK's framework, without it the SDK would not work.

**Comment by schoes** [comment]
i've installed via manual installation
and think that i got all the files

**Comment by dcirne** [comment]
The manual installation requires a few other steps, including the creation and positioning of a **Run Script**. Could it be that the script is not doing the right thing at the right time in your project?

The main purpose of the script is to strip the library's binary of the non-needed architectures, leaving only the required ones. When running in the simulator (x86_64) and when running on devices (arm7 and arm64).

**Comment by schoes** [comment]
![screen shot 2018-05-29 at 15 44 48](https://user-images.githubusercontent.com/3438263/40662641-3de3be4e-6357-11e8-92bd-85772feae767.png)

this are the build phases

**Comment by dcirne** [comment]
From what we can see it seems that the configuration is correct. There must something small that is amiss.

Is this a sample project or your app? If a sample project, you can zip it and sent to us using the support email (https://github.com/Clarifai/clarifai-apple-sdk#support). Or we can create a sample project and send to you. Which one would you prefer? Also, are you using Swift or Objective-C? It doesn't make a difference, just asking to know which language to use if you'd like us to send you a sample project.

**Comment by schoes** [comment]
it is my app and it's written in swift

**Comment by schoes** [comment]
i've found the problem when deploying onto a simulator it strips down the Clarifai SDK to 37 MB and when deploying to the device again its too small. what could be the problem ?

**Comment by dcirne** [comment]
This is not the problem @schoes , it is the expected behavior. The main job of the script is to remove the non-related architectures from the library's binary.

When you run in the simulator the script removes the architectures for on-device (arm7 and arm64), leaving only x86_64.

And when running on a device, the script removes the architecture for in-simulator (x86-64).

The issue I was describing on the email is that the `Clarifai_Apple_SDK.framework.original` folder (created by the script) must contain the origin SDK packing all the architectures. From that directory the script will make a copy to the `Clarifai_Apple_SDK.framework` directory and strip the library's binary to leave it with only the required architectures for the intended target.

**Comment by schoes** [comment]
<img width="662" alt="screen shot 2018-05-29 at 17 31 43" src="https://user-images.githubusercontent.com/3438263/40669026-4358c28e-6366-11e8-9df0-c5a22fcfd371.png">
After i copied the framework again and take care of the framework oder -> take Clarifi SDK at the end the deployment to the device works.
Thanks for your help
