### ISSUE TITLE
When trying to install the pod through cocoapods I get the error 'detached from HEAD'

### ISSUE THREAD

**Issue by thijsheijden** [Clarifai/clarifai-apple-sdk#18]
When running the command 'pod install --repo-update I get the following error:

-> Installing Clarifai-Apple-SDK (3.0.0-beta17)
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/Clarifai/clarifai-apple-sdk.git
     /var/folders/4_/2_9zc4x977330kntwzq2s87h0000gn/T/d20180529-1157-ubzdnn
     --template= --single-branch --depth 1 --branch 3.0.0-beta17
     Cloning into '/var/folders/4_/2_9zc4x977330kntwzq2s87h0000gn/T/d20180529-1157-ubzdnn'...
     Note: checking out '44f751742ded167b693d6b091f3d8d712b34a829'.
     
     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by performing another checkout.
     
     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -b with the checkout command again. Example:
     
       git checkout -b <new-branch-name>
     
     git-lfs filter-process: git-lfs: command not found
     fatal: The remote end hung up unexpectedly
     warning: Clone succeeded, but checkout failed.
     You can inspect what was checked out with 'git status'
     and retry the checkout with 'git checkout -f HEAD'
     

[!] Error installing Clarifai-Apple-SDK
[!] /usr/bin/git clone https://github.com/Clarifai/clarifai-apple-sdk.git /var/folders/4_/2_9zc4x977330kntwzq2s87h0000gn/T/d20180529-1157-ubzdnn --template= --single-branch --depth 1 --branch 3.0.0-beta17

Cloning into '/var/folders/4_/2_9zc4x977330kntwzq2s87h0000gn/T/d20180529-1157-ubzdnn'...
Note: checking out '44f751742ded167b693d6b091f3d8d712b34a829'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

git-lfs filter-process: git-lfs: command not found
fatal: The remote end hung up unexpectedly
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by dcirne** [comment]
Hi @thijsheijden 

It seems you are missing Git LFS. Please install it as per instructions in the README (https://github.com/Clarifai/clarifai-apple-sdk#git-lfs) and try installing the SDK again.

Git LFS is used to download the binary library inside the SDK's framework.
