### ISSUE TITLE
Error training models with beta 17

### ISSUE THREAD

**Issue by Shoshin23** [Clarifai/clarifai-apple-sdk#19]
Hi Team, 

I've been trying to train models on device with the latest beta but I always get the following error:
`Created training inputs
Created training inputs
Created training inputs
Created training inputs
Created training inputs
Created training inputs
Created training inputs
Created training inputs
Created training inputs
9
2018-06-12 12:04:36.658429+0200 EnvisionBeta[9553:1071539] [Common] _BSMachError: port 29713; (os/kern) invalid capability (0x14) "Unable to insert COPY_SEND"
2018-06-12 12:04:37.079917+0200 EnvisionBeta[9553:1071644] 📕 Clarifai:: Error training model.
Model trained succesfully!`

My code for training the model is as follows:

`var trainingInputs = [Input]()
        let trainingConcept = Concept(id: "customConcept", name: "cats", score: 1.0)
        let trainingConcepts = [trainingConcept]
        for trainingImage in self.imagesForTraining {
            let trainingCAIImage = Image(image: trainingImage)
            let trainingDataAsset = DataAsset(image: trainingCAIImage)
            trainingDataAsset.add(concepts: trainingConcepts)
            let input = Input(dataAsset: trainingDataAsset)
            trainingInputs.append(input)
            print("Created training inputs")
        }
        
        print(trainingInputs.count)
        let model = Model(id: "customModel2", name: "Prototype1")
        

        
        
        
        
        model.train(concepts: trainingConcepts, inputs:trainingInputs) { (error) in
            if ((error) != nil) {
                print("Problem with training the model")
                print(error?.localizedDescription)
                return
            }
            print("Model trained succesfully!")`
           Clarifai.sharedInstance().save(entities: [model])
           }

Do let me know if I'm doing something wrong. My general model seems to work perfectly fine.

**Comment by Shoshin23** [comment]
The funny bit was it was working fine when i had beta10 so far. Today when i reopened the project for a presentation at my workplace, the app was crashing. I updated the pods to test it out. 

The general model works just fine but the custom models aren't working at all.

**Comment by dcirne** [comment]
Thanks for the feedback @Shoshin23 we will take a look and try to reproduce the scenario you're describing.

One thing you may want to try is to declare `model` as a variable, instead of a constant. The `train` method will modify the instance.

**Comment by Shoshin23** [comment]
Hi @dcirne, 
Thanks for the tip. Unfortunately changing model to var isn't working for me. I still can see that the training has failed. But interesting though, there was `error` is nil. 

Also, I changed the model variable from a local variable to a global variable in the beginning of the ViewController but still no change. I don't get the `📕 Clarifai:: Error training model.` error but looks like the training is stuck. 

Thanks!

**Comment by Shoshin23** [comment]
Sorry, I closed it by mistake. The issue is still open.

**Comment by bnovie** [comment]
Looking into this error message and any hint of what could cause it.

> _BSMachError: port 29713; (os/kern) invalid capability (0x14) "Unable to insert COPY_SEND"

https://stackoverflow.com/questions/39676762/error-bsmacherror-port-1607-os-kern-invalid-capability-0x14-unable-to-i

Has anything else changed or updated ?

It sounds weird but a developer with this problem deleted their breakpoints and it fixed the issue.

**Comment by Shoshin23** [comment]
Hi @bnovie,
I didnt change anything with the code. I used to run beta 10 and that kept crashing my system. I then updated to beta 17 thinking the old beta was deprecated. That's when I got the problem. And when i try to call my customModel, I get a "Model has not been trained" error. 

I'm trying to setup a new project altogether and see if it's an issue with the sdk or my project.

**Comment by Shoshin23** [comment]
So I created a new project to run clarifai sdk beta 17. This was the code I tested this on:

`    @IBAction func btn(_ sender: UIButton) {
        var trainingInputs = [Input]()
        let trainingConcept = Concept(id: "customConcept", name: "airpods", score: 1.0)
        let trainingConcepts = [trainingConcept]
        for trainingImage in self.imageUrls {
           
            let trainingCAIImage = Image(image: trainingImage)
            let trainingDataAsset = DataAsset(image: trainingCAIImage)
            trainingDataAsset.add(concepts: trainingConcepts)
            let input = Input(dataAsset: trainingDataAsset)
            trainingInputs.append(input)
            print("Created training inputs")
        }
        
        print(trainingInputs.count)
        
        var model = Model(id: "customModel", name: "EnvisionModel")
        
        model.train(inputs: trainingInputs) { (error) in
            if error != nil {
                NSLog("Custom model training failed with error \(String(describing: error))")
                return
            }
            print("Model trained")
            
            
        }
    }`

I get a bad memory access error from Xcode when I run this. 
`warning: could not execute support code to read Objective-C class data in the process. This may reduce the quality of type information available.`

I'm using this with iOS 11.4, Xcode 9.4 and Swift 4.1. Hope this helps. :)

**Comment by Shoshin23** [comment]
The Dexter project that is part of the clarifai repo works just fine. I'm not sure what's the issue with my code though. Debugging mine with that as the reference.

**Comment by fat1diabl0** [comment]
Hi Team, 

I'm still facing this issue and have been trying to fix this for over 2 weeks now. I've tried all of the following: 
1) roll back my code - didnt work
2) roll back to older version of the sdk . - didnt work.
3) Delete all new pods - didnt work. 

This is a pretty novel feature of our app and it being down isn't an ideal situation. 

Thanks!
