### ISSUE TITLE
Apple Mach-O Linker Error

### ISSUE THREAD

**Issue by orazz** [Clarifai/clarifai-apple-sdk#2]
Xcode 8.3.1
```import Clarifai_Apple_SDK```
```Clarifai.sharedInstance().start(appKey:"my api key")```

![screen shot 2017-08-04 at 3 19 20 pm](https://user-images.githubusercontent.com/8214953/28964938-63c81124-7928-11e7-8299-02312dd515d7.png)

**Comment by dcirne** [comment]
Thanks for submitting the issue @orazz 

I'm assuming you're using a manual installation, rather than CocoaPods. If that is the case:

* Have you included the SDK in **Embedded Binaries**? 
* Have you included the required dependencies?

I pasted this screenshot to illustrate the questions above.

![cleanbuild](https://user-images.githubusercontent.com/204792/28969178-79b06996-78f1-11e7-830f-ed55a88fcc42.jpeg)

Let me know if this fixes the linker error.

**Comment by orazz** [comment]
Firstly i installed this library by cocoapod, but it didn't work, after u answer, i did it manually:

<img width="635" alt="screen shot 2017-08-04 at 7 05 43 pm" src="https://user-images.githubusercontent.com/8214953/28972200-2db75e6c-7948-11e7-96f5-6a2cedc8c39d.png">

result:

<img width="253" alt="screen shot 2017-08-04 at 7 08 14 pm" src="https://user-images.githubusercontent.com/8214953/28972260-64a1c6ba-7948-11e7-976f-a28836fb3d7c.png">

I think problem with architecture

<img width="884" alt="screen shot 2017-08-04 at 7 09 36 pm" src="https://user-images.githubusercontent.com/8214953/28972323-b78f6a9e-7948-11e7-854f-62d690767f36.png">

**Comment by dcirne** [comment]
It seems that the project, as configured, is expecting the library inside the SDK to be available at the directory listed: `-F.../TestClarifai/Pods/Clarifai-Apple-SDK`.

Regarding architecture, the SDK is build and deployed for all needed architectures: `armv7`, `armv7s`, `arm64`, `i386`, and `x86_64`.

Have you tried creating a simple project from scratch and add the SDK (either manually or via CocoaPods)?

**Comment by orazz** [comment]
I deleted old project created new one and added lib manually:

<img width="875" alt="screen shot 2017-08-04 at 7 25 16 pm" src="https://user-images.githubusercontent.com/8214953/28972956-265ebd7e-794b-11e7-8d16-c5e4c5b509f6.png">

**Comment by dcirne** [comment]
@orazz 

Listed below are references to two sample projects using the SDK. One in Objective-C and the other in Swift. In both cases the projects compile, link, and run correctly in the simulator and on device.

[**Objective-C** sample](https://drive.google.com/file/d/0BwNPvxOKz9wUdkREbkhodDRlcHc/view?usp=sharing)

[**Swift** sample](https://drive.google.com/file/d/0BwNPvxOKz9wUcGRUTWphdjQyaTA/view?usp=sharing)

Those were generated using Xcode 8.3.3 and have deployment target of iOS 8.2.

**Comment by orazz** [comment]
Thanks, It works.
Clarifai_Apple_SDK file size you sent

<img width="336" alt="screen shot 2017-08-04 at 8 30 35 pm" src="https://user-images.githubusercontent.com/8214953/28975556-e300ce24-7953-11e7-8dda-ba3c27b407be.png">

Clarifai_Apple_SDK file size when I clone it from GitHub

<img width="397" alt="screen shot 2017-08-04 at 8 30 42 pm" src="https://user-images.githubusercontent.com/8214953/28975649-3d6da512-7954-11e7-9449-1b36d72c6d33.png">

**Comment by dcirne** [comment]
The binary contained in the framework is managed by GitHub using `git-lfs`. I wonder if you have it installed on your system.

If not, you can see how to get it at: https://git-lfs.github.com

You can install it via Homebrew, MacPorts, or direct download.

**Comment by orazz** [comment]
Thanks! The problem has been solved.

**Comment by marjan80** [comment]
@dcirne 
I'm having the same issue and cannot fix it. I have done all the steps. 
I did the manual installation. The file sizes are right. I also could initialise git-lfs but don't know how to check if it's installed properly.
Could you please help me out to fix this issue?
Btw, the sample projects are not available.

**Comment by dcirne** [comment]
Hi @marjan80 

You can find the sample project under the `Examples` folder: https://github.com/Clarifai/clarifai-apple-sdk/tree/master/Examples/Dexter

If you installed Git LFS after cloning the SDK, you'd need to do it again.

Also, did you add the SDK framework to your project's **Embedded Binaries**?

Last, but not least, did you create a new **Run Script Build Phase** to run the _setup_framework.sh_ script?

**Comment by marjan80** [comment]
Hi @dcirne 
Thank you so much.
Cloned the project **after** installing GIT LFS, and it solved the problem. The code compiles now.
