### ISSUE TITLE
Signal SIGABRT while loading Clarifai_Apple_SDK

### ISSUE THREAD

**Issue by diegobalbi** [Clarifai/clarifai-apple-sdk#20]
Hi Team,
I git-cloned Clarifai/clarifai-apple-sdk and tried running Examples/Dexter at XCode.

It does not work. It shows:
`dyld: Library not loaded: @rpath/Clarifai_Apple_SDK.framework/Clarifai_Apple_SDK
  Referenced from: /Users/diego/Library/Developer/CoreSimulator/Devices/2260E865-82C6-43A1-A7B5-2DA4C59AC7E6/data/Containers/Bundle/Application/E52E1EE6-13F2-452A-82DA-E639F622A68F/Dexter.app/Dexter
  Reason: image not found`.

I see Clarifai_Apple_SDK is at clarifai-apple-sdk/Clarifai_Apple_SDK.framework and its size seems to be the correct one: -rwxr-xr-x 1 diego staff 302088168 Jul 12 15:20 Clarifai_Apple_SDK
`# file Clarifai_Apple_SDK

Clarifai_Apple_SDK: Mach-O universal binary with 3 architectures: [x86_64:Mach-O 64-bit dynamically linked shared library x86_64] [arm64]
Clarifai_Apple_SDK (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
Clarifai_Apple_SDK (for architecture armv7):	Mach-O dynamically linked shared library arm_v7
Clarifai_Apple_SDK (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64`

Can you help me solve the problem?!

Before, I tried writting my own "Hello Clarifai" application by following "Getting Started" at https://github.com/Clarifai/clarifai-apple-sdk, it did not work either... I will tell you more details about this try if you want. But I believe that to get your example running should be simpler and faster, shouldn't it?

My computer is MacBook Pro (Retina, 15-inch, Mid 2015).
Thanks a lot!

**Comment by dcirne** [comment]
Hi @diegobalbi , thanks for your feedback.

It seems that you may not have Git-LFS installed. It is one of the required steps (https://github.com/Clarifai/clarifai-apple-sdk#git-lfs)

Give it a try.

**Comment by diegobalbi** [comment]
Thank you Dalmo!

A couple days ago, I got an error after a while during installation using brew install git-lfs . Afterwards, I tried unziping the tar.gz also suggested at git-lft.github.com and running install.sh . It fastly copied git-lfs to /usr/local/bin and said "Installed".

How can I know if it is properly installed? Does the following output help you answer me? : 
`>cd clarifai-apple-sdk/
>git lfs status
On branch master
Git LFS objects to be pushed to origin/master:

Git LFS objects to be committed:

Git LFS objects not staged for commit:
        Examples/Dexter/Dexter.xcodeproj/project.pbxproj (Git: 34c7c6d -> File: ea99834)
	Examples/Dexter/Dexter/AppDelegate.swift (Git: 08be62d -> File: 3655a94)
	Examples/Dexter/Dexter/Base.lproj/LaunchScreen.storyboard (Git: d994945 -> File: 1762bd4)
	Examples/Dexter/Dexter/Base.lproj/Main.storyboard (Git: 80debd6 -> File: 2151e52)
`
I appreciate your help! 
Regards

**Comment by dcirne** [comment]
@diegobalbi you should be able to see if the installation was properly done by switching to the repo directory and typing `git lfs env`.

If you were having issues installing Git LFS, I'm afraid you will need to re-install the Clarifai-Apple-SDK from the beginning. Unzipping the .tar will not help you, as GitHub does **not** include the binary of the framework. That is exactly the reason why we need Git LFS installed, as it manages large files in the repository.

You seem to be almost there. Consider a fresh install and things should just work.

**Comment by diegobalbi** [comment]
Now I believe git-lfs installed because of two reason:
**First:**

> git lfs env
> git-lfs/2.4.2 (GitHub; darwin amd64; go 1.10.2; git 6f4b2e98)
> git version 2.14.3 (Apple Git-98)
> 
> Endpoint=https://github.com/Clarifai/clarifai-apple-sdk.git/info/lfs (auth=none)
> LocalWorkingDir=/Users/diego/code/clarifai-apple-sdk
> LocalGitDir=/Users/diego/code/clarifai-apple-sdk/.git
> LocalGitStorageDir=/Users/diego/code/clarifai-apple-sdk/.git
> LocalMediaDir=/Users/diego/code/clarifai-apple-sdk/.git/lfs/objects
> LocalReferenceDir=
> TempDir=/Users/diego/code/clarifai-apple-sdk/.git/lfs/tmp
> ConcurrentTransfers=3
> TusTransfers=false
> BasicTransfersOnly=false
> SkipDownloadErrors=false
> FetchRecentAlways=false
> FetchRecentRefsDays=7
> FetchRecentCommitsDays=0
> FetchRecentRefsIncludeRemotes=true
> PruneOffsetDays=3
> PruneVerifyRemoteAlways=false
> PruneRemoteName=origin
> LfsStorageDir=/Users/diego/code/clarifai-apple-sdk/.git/lfs
> AccessDownload=none
> AccessUpload=none
> DownloadTransfers=basic
> UploadTransfers=basic
> git config filter.lfs.process = "git-lfs filter-process"
> git config filter.lfs.smudge = "git-lfs smudge -- %f"
> git config filter.lfs.clean = "git-lfs clean -- %f"

**Second:**
I believe that git-lfs worked. Why? Because I see the library file  (rather than a file with reference to it)
> ls -l clarifai-apple-sdk/Clarifai_Apple_SDK.framework/Clarifai_Apple_SDK 
> -rwxr-xr-x 1 diego staff 302088168 Jul 12 15:20 clarifai-apple-sdk/Clarifai_Apple_SDK.framework/Clarifai_Apple_SDK .

Am I wrong?

Last but not least! I've said I can see Clarifai_Apple_SDK.framework/Clarifai_Apple_SDK in the git working copy (real file and correct size), but it is NOT in the mobile simulator, as you can see in my first message in this thread! May it be possible I should configure in Xcode project something that has not been pushed to git branch by your Team?

Thanks!!

**Comment by dcirne** [comment]
@diegobalbi everything has been pushed to the repository. There are no missing files. Let's work on your installation.

Have you installed via CocoaPods or manually?

If you installed manually, have you added the `setup_framework.sh` script to Xcode (https://github.com/Clarifai/clarifai-apple-sdk#manual-installation)?

The purpose of the script is to strip the framework's binary from the architectures it doesn't need and leave only the one for the target platform. For example, if you run in the simulator, the script will strip armv7 and arm64, leaving only x86_64. And the other way around if you run on a device.

**Comment by diegobalbi** [comment]
I've tried so many options (about git-lft, pod install and others) both in Dexter and in my own project, that now I cannot tell if I had run "pod install --repo-update" in Dexter folder...
In any case, I have just run "pod install" regards to your comment, and Dexter has started up for the very first time!
I hope everything is ready to go ahead with my test and development now.
Thank you very much!
Kind and best regards

**Comment by dcirne** [comment]
Great to hear things are working!
