### ISSUE TITLE
Loading models from the cloud?

### ISSUE THREAD

**Issue by calee14** [Clarifai/clarifai-apple-sdk#21]
Hello team,
So right now I'm making an app in swift and I'm having trouble in trying to load your food model. I have your Apple SDK installed and I'm looking at the documentation for the SDK. It's programmed in Obj-C so I'm having trouble trying to convert it into swift. Is there a way to load one of your models from the Cloud?

**Comment by dcirne** [comment]
Hi @calee14 , thank you for the feedback.

Currently the SDK only supports the General Model. We are currently working on supporting other models. This will come as a new feature on a future release. There is no ETA, yet.

**Comment by calee14** [comment]
Should I for now use the clarify-ios repo to access your models?

**Comment by dcirne** [comment]
Yes, you can do that. Just be aware that the inference engine will not be on the device. The [clarifai-ios](
https://github.com/Clarifai/clarifai-ios) is a wrapper for the API. The device will be making network calls and the instructions will be executed in the cloud.

**Comment by calee14** [comment]
That's fine. As long as I can access the your models everything should be fine. 
Thanks.
