### ISSUE TITLE
Error via pods

### ISSUE THREAD

**Issue by kalyan711987kalyan** [Clarifai/clarifai-apple-sdk#22]
I download the sample and installed the pods. Getting below errors. 
Can you please help?
![screen shot 2018-07-30 at 6 15 20 pm](https://user-images.githubusercontent.com/1528160/43398090-a949ab32-9424-11e8-80af-a50511a0a1e4.png)

**Comment by jpgsloan** [comment]
Do you have Git-LFS installed on your machine? If not, you can find the installation instructions at https://git-lfs.github.com. Git LFS is required for both CocoaPods and manual installations

Also make sure to update your local CocoaPods repository. You may need to force upgrade your local, cached, repository with: pod install --repo-update

**Comment by kalyan711987kalyan** [comment]
Sorry for late repay.

I have Git LFS installed. Also update pods repo. Done a clean build. Still same issue.

**Comment by dcirne** [comment]
@kalyan711987kalyan in case you installed Git LFS afterwards, you will need to re-do the process from the beginning.

In case it still doesn't work for you, could you please create a sample project and make it available for us to download? You can send an email to <mobile-feedback@clarifai.com> with downloading instructions.

We will try your sample project and help you figure out what is amiss.

**Comment by kalyan711987kalyan** [comment]
I have sent the steps and project zip over mail

Thank you.

**Comment by dcirne** [comment]
Thanks for sending your project @kalyan711987kalyan 

Question for you. Did you have Git LFS installed prior to cloning the repository? If not, you will need to clone it again, since the binary library of the SDK will not have been downloaded.

**Comment by kalyan711987kalyan** [comment]
Yes I have Git LFS, I have cloned the repository just few mins back and tried to build the project.

**Comment by jpgsloan** [comment]
Hi @kalyan711987kalyan, I've just taken a look at the sample project you emailed to us. The issue is indeed that you installed git LFS **after** cloning the repo. The **Clarifai_Apple_SDK.framework** file in your project is only 243Kb, but it should be over 200mb when probably cloned. 

I suggest starting from scratch and deleting the repo locally. Then try recloning the repo and make sure that the file size of **Clarifai_Apple_SDK.framework** exceeds 200mb.

**Comment by kalyan711987kalyan** [comment]
Thank John for reply.
 After Git LFS installed, I made fresh clone, still Clarifai_Apple_SDK.framework size is in Kb's. 
Let me know, If anything I'm missing.

Git LFS version below are details:
**git lfs env**
git-lfs/2.5.1 (GitHub; darwin amd64; go devel +bd98a81dc2 Thu Jul 26 17:13:12 2018 +0000; git e1628484)
git version 2.15.1 (Apple Git-101)

Endpoint=https://github.com/Clarifai/clarifai-apple-sdk.git/info/lfs (auth=none)
LocalWorkingDir=/Users/kalyan/Downloads/git-lfs-darwin-amd64-v2.5.1/clarifai-apple-sdk
LocalGitDir=/Users/kalyan/Downloads/git-lfs-darwin-amd64-v2.5.1/clarifai-apple-sdk/.git
LocalGitStorageDir=/Users/kalyan/Downloads/git-lfs-darwin-amd64-v2.5.1/clarifai-apple-sdk/.git
LocalMediaDir=/Users/kalyan/Downloads/git-lfs-darwin-amd64-v2.5.1/clarifai-apple-sdk/.git/lfs/objects
LocalReferenceDirs=
TempDir=/Users/kalyan/Downloads/git-lfs-darwin-amd64-v2.5.1/clarifai-apple-sdk/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/Users/kalyan/Downloads/git-lfs-darwin-amd64-v2.5.1/clarifai-apple-sdk/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
