### ISSUE TITLE
Clarifai slow start

### ISSUE THREAD

**Issue by FallenDestiny** [Clarifai/clarifai-apple-sdk#23]
After appdelegate's didFinishLaunchingWithOptions, clarifai send me warning "_Clarifai:: Failed to open zip file_" , and doesn't work until the last warning appear :
<img width="1987" alt="screen shot 2018-09-14 at 12 55 26" src="https://user-images.githubusercontent.com/43267774/45543793-30ad6600-b81e-11e8-98ee-90a8856f729d.png">

Framework don't work util last warning appear , request are sent but i can't get the response from server. I must wait from 1 to 5 minute until warnings appear.

 Git-LFS is installed, repo update already done. Please help!

**Comment by dcirne** [comment]
Hello @FallenDestiny,

The SDK first needs to authenticate itself against the cloud, which requires _all scopes_ permission, then fetch the model and cache it locally.

The console log you sent seems to be showing that the fetched model was somehow corrupted, or there is an incorrect file in its place with the same name. It could be something else; hard to tell without context.

The recommendations would be to check the permissions of your API Key, delete the app and run again. Also, given the amount of time you say you must wait, I'd check your internet connection speed as well. The model is not big, but still needs to be fetched from the cloud.

**Comment by dcirne** [comment]
@FallenDestiny we have made a release of the SDK today, which most likely will address the issue you are seeing. Please upgrade to version `3.0.0-beta24` and try again. 
```bash
pod install --repo-update
```
Things should just work.

**Comment by nikeshakya** [comment]
@dcirne  I am still experience app freeze on app load (sometimes) because of clarifai..

**Comment by nikeshakya** [comment]
@dcirne where is reply to my question....I am using the latest beta25 and app still freezes on fresh start sometimes....it is becoming too much irritating now..if I remove my line to initialize clarifai..app never freezes again...!!!

**Comment by dcirne** [comment]
@nikeshakya can you send us a sample project reproducing the behavior you are experiencing? You can either send it to mobile-feedback@clarifai.com or it could be a public GitHub project.

Thank you.

**Comment by dcirne** [comment]
@nikeshakya

Please, don’t understant us wrong. I didn’t ask for your client’s project, but a sample project reproducing the behavior you are seeing.

Sample project in the sense that it is a piece of code, specially built to reproduce what you are describing, but does not contain proprietary code or any of your, or your client, intellectual property.
