### ISSUE TITLE
Xcode not exiting completion handler for model.predict (using general model)

### ISSUE THREAD

**Issue by fellowProgrammer** [Clarifai/clarifai-apple-sdk#25]
I have a function in which you pass in an image and it returns you the 20 tags Clarifai suggests (at least it is supposed to). However, Xcode never seems to exit the completion handler. I have come to this conclusion by using a series of print statements (see below).

Code... 
```
  model.predict(inputs, completionHandler: {(outputs: [Output]?,error: Error?) -> Void in
        for output in outputs! {
            let concepts = output.dataAsset.concepts
            print(concepts?.count)
            for concept in concepts! {
                print(concept.name)
                subjects.append(concept.name)
            }
        
            print("done")  //Done is printed
        }
        print("done2") //Done is printed
        print(subjects) // Subjects are printed
    })
    
    
print("done3") //Done 3 is NOT printed
    print(subjects) //Subjects are NOT printed
    return subjects //Subjects are NOT returned
}
```

This might be a very simple issue to solve, but I just can't figure out what I am doing wrong.

**Comment by fellowProgrammer** [comment]
Sorry, this

**Comment by fellowProgrammer** [comment]
Sorry this was a logical error on my part. Since it takes a while for the Clarifai SDK to recieve the tags, it printed the information after the rest of the function, making it seem like the print statements outside of the completion handler were not being called. Bit in fact there were just being called earlier and I didn’t see them. In short I was expecting my code to run aysnchronsly.

**Comment by joninsky** [comment]
I recommend remove the Clarafai pod and then running `pod cache clean --all` Then re-install.
