### ISSUE TITLE
SDK crashes if image > 1 MB. 

### ISSUE THREAD

**Issue by Shoshin23** [Clarifai/clarifai-apple-sdk#26]
Hi, 

The current beta of the Clarifai SDK crashes when I try to pass an image more than 1 MB. I'm not sure why this is happening or if it's something basic that I'm missing. Would like to know if this is the case and how I should optimise the images necessary for training. 

Regards, 
Karthik

**Comment by dcirne** [comment]
Hi @Shoshin23 

Could you send us a sample application, and a sample image, reproducing the scenario you are experiencing?

Once you have it ready, you can send it to: <mobile-feedback@clarifai.com>

Thank you
