### ISSUE TITLE
Sample code/app needed to use the SDK better. 

### ISSUE THREAD

**Issue by Shoshin23** [Clarifai/clarifai-apple-sdk#3]
Hi, 

I was just starting to use the SDK and ran into a few issues, any help with this would be greatly appreciated: 

1) I was unable to install the sdk through cocoapods. The error was no such `[!] Unable to find a specification for Clarifai-Apple-SDK (= 3.0.0-beta2)`. 
I could install it manually without any problems though. 

2) I followed the examples on the docs page of Clarifai but unable to get a proper reasonable. 
        
       override func viewDidLoad() { 
       // Do any additional setup after loading the view, typically from a nib. 
       super.viewDidLoad()
        let testUIImage = UIImage(named: "Bus.JPG")
        let testImage = Image(image: testImageCreation)
        let dataAsset = DataAsset(image: testImage)
        let input = Input(dataAsset: dataAsset)
        let generalModel:Model? = Clarifai.sharedInstance().generalModel
        generalModel?.predict([input], completionHandler: { (results, error) -> Void in
            for output:Output in results! {
                print(output.dataAsset.concepts)
                for concept:Concept in output.dataAsset.concepts! {
                    print(concept.name)
                    
                }
            }
        })
    }`

I get a fixed output for every image I try to upload. Can you guys please put out a sample app that would help us understand Clarifai's lingo a little better?

Thanks.
Karthik

**Comment by dcirne** [comment]
Hi @Shoshin23 

Thanks for the feedback.

Yes, a sample app will be added in a future release. That will help with understanding and using the SDK.

Regarding installing the SDK with CocoaPods, you may want to do a repo update (`pod install --repo-update`). That will force CocoaPods to refresh your local repo and will install the Clarifai SDK.

About using the SDK, may I ask you a couple questions:
1) Are you starting the SDK prior to using any other command?
```swift
Clarifai.sharedInstance().start(appKey:"<App key goes here>")
```
2) Are you using a valid App Key to start the SDK?

**Comment by Shoshin23** [comment]
Hey @dcirne, 

Thanks for the repo-update suggestion. Will try it out. 

I'm starting the SDK in my app delegate as mentioned in the README in the repo. I also believe i'm using valid App Key. I got that from the "API Keys" section of my Clarifai dasbhoard. 

![api_keys___clarifai_developer](https://user-images.githubusercontent.com/2094133/28988730-f2b3f4dc-798e-11e7-8f76-74975148439e.jpg)

Do let me know if I'm doing something wrong here. 

Thanks, 
Karthik

**Comment by orazz** [comment]
I think a problem with app key because when I set appKey debug area shows this error:

```TestClarifai[29627:11970900] unknown NSNumber```

```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        Clarifai.sharedInstance().start(appKey:"c*****ce9")
        return true
    }
```

**Comment by Shoshin23** [comment]
The repo-update worked just fine for me. 

I get the same "unknown NSNumber" error like @orazz here. Didn't know if it is something to do with my app key.

**Comment by FKSI** [comment]
Have you tried a `Clean` of your workspace? I had some trouble with XCode and the SDK, but after a `Clean` and a XCode `Restart` everything if working since then

**Comment by dcirne** [comment]
@orazz , @Shoshin23 , @FKSI 

The `unknown NSNumber` is a known issue and will be fixed on a future SDK release. The good news it that the message is harmless. It is just an `NSLog` in a wrong place.

You can continue using the SDK and safely ignore the message output to the console.

**Comment by dcirne** [comment]
@Shoshin23 

Regarding the fixed output, which version are you running? `3.0.0-beta2`?

If yes, could you send the logs to the console or a screenshot with the outputs?

**Comment by orazz** [comment]
Finally, it works thanks. But I can't debug in real device 

![screen shot 2017-08-07 at 8 42 36 pm](https://user-images.githubusercontent.com/8214953/29034219-0286d176-7bb1-11e7-9063-b9c5e2c3b15a.png)

Is it required to register bundle id in developer account?

**Comment by dcirne** [comment]
@orazz the issue has nothing to do with the SDK.

![xcode_signing](https://user-images.githubusercontent.com/204792/29034484-655953b4-7b66-11e7-81d2-4a5842d4b996.jpeg)

You can change the team and the signing information in the Xcode project **General** tab, under the **Signing** section.

**Comment by Shoshin23** [comment]
Hi. 
I just tried this with the latest update and it seems to be working. :)

**Comment by yaibait** [comment]
@orazz hello , Can you run on real device ?

**Comment by FKSI** [comment]
@yaibait I had no issue to run on a real device ;)

**Comment by dcirne** [comment]
Hi @yaibait, there are thousands of devices running the SDK at the moment.

Have you tried using our sample app in the [Examples](https://github.com/Clarifai/clarifai-apple-sdk/tree/master/Examples) directory?

Or, have you tried starting a new project and configuring the credentials from scratch?

The SDK is a framework, a piece of software that does **not** require any form of signature or credentials in Xcode.

**Comment by yaibait** [comment]
@dcirne I have tried your sample app and no issue, but when I start a new project i get issue

**Comment by dcirne** [comment]
@yaibait, have you tried including all the dependencies as listed in the [README](https://github.com/Clarifai/clarifai-apple-sdk/blob/master/README.md)? 

If you are using CocoaPods, try forcing an update of the local cache with `pod install --repo-update`. Also, make sure your `Podfile` is configured with the latest version:

```ruby
target '<Your Target>' do
    platform :ios, '8.2'
    use_frameworks!

    pod 'Clarifai-Apple-SDK', '3.0.0-beta6'
end
```

**Comment by yaibait** [comment]
@dcirne  I have used manual installation

**Comment by dcirne** [comment]
@yaibait have you followed the steps described in the [Manual installation](https://github.com/Clarifai/clarifai-apple-sdk/blob/master/README.md#manual-installation) section?

Please note the first entry of the enumeration to: _"Add the Clarifai-Apple-SDK.framework to your project's Embedded Binaries"_

**Comment by yaibait** [comment]
@dcirne Yes,I had do that :( , waiting  @orazz

**Comment by orazz** [comment]
@yaibait You can't build it on the real device or in simulator also?
What error did u get please upload the screenshot

**Comment by yaibait** [comment]
@orazz I can't build on real device . Same your problem above

**Comment by dcirne** [comment]
@yaibait, the is no problem with @orazz. He just needed to configure Xcode, under the **General** tab, and setup **Identity** and **Signing**.

And that is not related with the SDK. It is a requirement from Apple for you to have an account with them, and valid signed certificates on your computer.

Please refer to [Apple's documentation about certificates](https://developer.apple.com/support/certificates/)

**Comment by orazz** [comment]
@dcirne  I have dev account and set team to my own but it doesn't help I can't build on a real device

**Comment by yaibait** [comment]
Here my screen record 

https://drive.google.com/file/d/0B7dcx0aOz_zkaTVWZ21xb2JtTTA/view?usp=sharing

**Comment by yaibait** [comment]
@dcirne Only way I can build on real device is remove ClarifaiSDK , I think that not problem of Dev Account .

**Comment by dcirne** [comment]
@yaibait, can you check a data point for me?

Please change into the Clarifai SDK directory and verify the size of the binary library:

```bash
$ cd Clarifai_Apple_SDK.framework
$ ls -l
```

You should see something similar to the listing below:

```bash
$ ls -l
total 575744
-rw-r--r--   1 dalmo  staff     204800 Sep 20 16:00 110034.embed
-rwxr-xr-x   1 dalmo  staff  294570156 Sep 20 16:24 Clarifai_Apple_SDK
drwxr-xr-x  27 dalmo  staff        918 Sep 20 16:00 Headers
-rw-r--r--   1 dalmo  staff        714 Sep 20 16:24 Info.plist
drwxr-xr-x   3 dalmo  staff        102 Sep 20 16:00 Modules
```

What is the size of your `Clarifai_Apple_SDK` library binary?

**Comment by yaibait** [comment]
No problem with library size 
![screen shot 2017-09-21 at 10 38 31 pm](https://user-images.githubusercontent.com/2168823/30704692-a4677b96-9f1d-11e7-8871-edf8238e6462.png)
