### ISSUE TITLE
Value of type 'Model' has no member 'train'

### ISSUE THREAD

**Issue by KrLikeblue** [Clarifai/clarifai-apple-sdk#31]
Hello,

I downloaded your code and I am trying to run, but it is giving me error "Value of type 'Model' has no member 'train'" in TrainingController class

Can anyone help me please ?

Thanks

**Comment by dcirne** [comment]
Hello @KrLikeblue ,

The SDK does not currently offer training on a device. Training of a model is offered in our cloud services.

**Comment by KrLikeblue** [comment]
Hello,

So If I want to run your library in my iOS project, How can I achieve it ?

I saw other issues in which, people are having issues in running XCode project.

Thanks

**Comment by dcirne** [comment]
Glad to hear you're implementing the SDK into your app, @KrLikeblue 

The SDK works remarkably well. Sometimes it is the case people don't read the [README](https://github.com/Clarifai/clarifai-apple-sdk/blob/master/README.md) and skip the section about Git LFS. This is a fundamental step, and without it the SDK will **not** work.

If you haven't installed Git LFS in your system yet, we would recommend to do so and restart the steps from the beginning.

We're looking forward to seeing you using the SDK.

**Comment by KrLikeblue** [comment]
Hello,

I am trying to install Git LFS using MacPorts with this command "port install git-lfs" using Terminal app.

It successfully added Git LFS. Then I update cocoapods in dexter project using "pod update" then I opened dexter project and tried to run in simulator and device. but it is not working

It still says "Value of type 'Model' has no member 'train'"

Thanks

**Comment by jpgsloan** [comment]
Apologies, it looks like the dexter project is using an outdated version of the apple sdk. We will fix this ASAP. In the meantime, you can see a working example of the sdk in action in our recently released Clarity demo app https://github.com/Clarifai/clarity

Clarity is open source so you can see directly how to integrate the apple sdk into your own projects. Let us know if you have any trouble getting it started.

**Comment by jpgsloan** [comment]
The Dexter example app is now updated and working.
