### ISSUE TITLE
Working with custom trained models. 

### ISSUE THREAD

**Issue by Shoshin23** [Clarifai/clarifai-apple-sdk#4]
Hi guys, 

Was trying to work with custom trained models but was unable to get it off the ground. Any help with this would be greatly appreciated. 

Here's my code. Also pasting the console outputs below. 

         let image1 = UIImage(named: "image1.JPG")
         let CAImage1 = Image(image: image1)
        
        let image2 = UIImage(named: "image2.JPG")
        let CAImage2 = Image(image: image2)

        let image3 = UIImage(named: "image3.JPG")
        let CAImage3 = Image(image: image3)
        
        let macbookTrainingConcept = Concept(id: "macbook", name: "Karthik'sMacbook", score: 1.0)
        //let macbookTrainingConcept2 = Concept(id: "not-macbook", name: "Not Karthik's Macbook", score: 0.0)
        
        let macbookTrainingConcepts = [macbookTrainingConcept]
        
        let dataAsset1 = DataAsset(image: CAImage1)
        dataAsset1.add(concepts: macbookTrainingConcepts)
        
        let dataAsset2 = DataAsset(image: CAImage2)
        dataAsset2.add(concepts: macbookTrainingConcepts)
        
        let dataAsset3 = DataAsset(image: CAImage3)
        dataAsset3.add(concepts: macbookTrainingConcepts)
        
        let input1 = Input(dataAsset: dataAsset1)
        let input2 = Input(dataAsset: dataAsset2)
        let input3 = Input(dataAsset: dataAsset3)
        
        let trainingInputs = [input1,input2,input3]

        Clarifai.sharedInstance().save(entities: trainingInputs)
        
        
        //train the model
        let macbookModel = Model(id: "macbookModel", name: "Macbook Model")
        
        macbookModel.train(concepts: macbookTrainingConcepts, inputs: trainingInputs) { (error) in
            if ((error) != nil) {
                print("Problem with training the model")
                print(error)
                return
            }
            print("Model trained successfully.")
                   }
        
        
        
    }

          @IBAction func testCustomModel(_ sender: Any) {
        
                let testUIImage = UIImage(named: "testImage.JPG")
                 let testImage = Image(image: testUIImage)
                let dataAsset = DataAsset(image: testImage)
                let input = Input(dataAsset: dataAsset)
        
        let customModel = Model(id: "macbookModel", name: "Macbook Model")
        print(customModel.createdDate)
        print(customModel.appId)
        print(customModel.name)

        customModel.predict([input]) { (results, error) in
           if (error != nil) {
                print(error)
                return
            }
            print(results)
        }
    }

Here's the error I'm getting when I try this. I wait for the "Model Successfully trained" message and then press the button screen to test it out. Pasting my logs

![custommodellogs](https://user-images.githubusercontent.com/2094133/29487002-40445c3c-8510-11e7-8d69-3a7cd12a5fde.jpg)

Please let me know if I'm doing something wrong here. Again, a sample app walking us through would be great!

Thanks!

**Comment by Shoshin23** [comment]
Interesting thing to note here is that my app's size has ballooned ever since trying out the custom model aspect of the SDK. So I'm guessing that the model is "saved" but not usable. :)

**Comment by dcirne** [comment]
@Shoshin23 

It seems you're creating two separate model instances sharing the same id and name:

```swift
let macbookModel = Model(id: "macbookModel", name: "Macbook Model")
and
let customModel = Model(id: "macbookModel", name: "Macbook Model")
```

Instead, let's try to save and load the model you trained instead:

```swift
// Create the model
let macbookModel = Model(id: "macbookModel", name: "Macbook Model")

// Train the model 
...

// Save the model
Clarifai.sharedInstance().save(entities: [macbookModel])

// Someplace else in the code you can load the model that has been previously 
// trained and saved
Clarifai.sharedInstance().load(entityId: "macbookModel", entityType: .model) { (model, error) in
    guard let customModel = model as? Model else {
        return
    }
    print(customModel.name)
}
```

**Comment by Shoshin23** [comment]
Thanks @dcirne!

The model seems to be training just fine. But here's an issue I'm facing. Irrespective of what image i feed it it's always predicting it as Macbook Air. How do I train "Not-A-Macbook-Air" images to it? What should my training data look like?

Here's the new sample code I've written for prediction

        Clarifai.sharedInstance().load(entityId: "macbookModel", entityType: .model) { (model, erro) in
            guard let customModel = model as? Model else {
                return
            }
            customModel.predict([input], completionHandler: { (outputs error) in
                for op in outputs! {
                    print(op.dataAsset.concepts)
                    for concept:Concept in op.dataAsset.concepts! {
                        print(concept.name)
                        
                    }
                }
            })
            print(customModel.name)
            //print(customModel.output)
            print(customModel.createdAt)
        }

Thanks!

**Comment by dcirne** [comment]
@Shoshin23 

Are you checking the scores of the outputs? 

```swift 
for concept:Concept in op.dataAsset.concepts! {
    print("name: \(concept.name) score: \(concept.score)")
}
```

Scores will range between `0` and `1`, informing the degree of confidence of the prediction.

If necessary, you can also provide more training data with concepts containing positive images (score 1) and/or negative images (score 0). For example:

```swift
let notAMacbookConcept = Concept(id: "macbook", name: "Karthik'sMacbook", score: 0.0)
```

Note that the concept above has the same name as the positive concept, but has a score of `0.0`. This concept should be associated with a non Macbook image. By having a positive concept (`score = 1.0`) associate with a Macbook image, and a negative concept of same id and name (`score = 0.0`) associated with a non-Macbook image, you'd be fine tuning the training of the model.

**Comment by Shoshin23** [comment]
Yup. I just realised it after I posted the issue. The score is (understandably) lower for a non-macbook image. I'll be using custom training to mostly train models on the fly for my users so not sure about how to get negative concepts from users. Also, how many images do you think is required for the model to do a decent job of classifying objects, any minimum threshold? 

Also, would I be able to update my model with different concepts? Like say classify a Dell Laptop or an iPad? 

Thanks!

**Comment by dcirne** [comment]
The nuances of the interface I will leave to you, but you can have something like a thumbs-up 👍for positive feedback and a thumbs down 👎 for a negative one, those translating internally as `1` or `0`.

Regarding the number of images, this is an empirical experiment where you may need to find the optimal number for your case. Perhaps 10 or 15 images are enough.

We're really excited to see you using the SDK and applying it to your app. I'd like to introduce you to our team and see ways to take this partnership to the next level.
