### ISSUE TITLE
Cannot install on real device 

### ISSUE THREAD

**Issue by yaibait** [Clarifai/clarifai-apple-sdk#5]
I try install to a real device and get this :
<img width="478" alt="screen shot 2017-09-19 at 2 46 54 pm" src="https://user-images.githubusercontent.com/2168823/30581180-6bb44548-9d49-11e7-8225-dd09ebeb1377.png">
I had signed app with my developer account

**Comment by dcirne** [comment]
Hi @yaibait ,

The SDK does not require any kind of signing. It seems you need to configure your **Identity** and **Signing** in Xcode, under the project's **General** tab.

The picture below is an example of the configuration referenced on the line above.

![xcode signing](https://user-images.githubusercontent.com/204792/30592363-7350dbc0-9d14-11e7-8a6b-c4859210032c.jpeg)

**Comment by yaibait** [comment]
@dcirne  thanks you, I had tried that on objective-c project but seem not work

**Comment by dcirne** [comment]
@yaibait I am not sure if there is anything we can do to help you. What you are experiencing is not related to the Clarifai SDK, but seems to be something related to your account credentials with Apple.

**Comment by dcirne** [comment]
@yaibait today we released a new version of the SDK, including new instructions for the [Manual Installation](https://github.com/Clarifai/clarifai-apple-sdk#manual-installation). The new process includes a **Build Phase** running a script.

It is likely that this release and the new instructions will work for you.
