### ISSUE TITLE
 Error installing Clarifai-Apple-SDK 3.0.0-beta8

### ISSUE THREAD

**Issue by heng2j** [Clarifai/clarifai-apple-sdk#6]
Hi Team,

When I follow the instruction to install Calrifai with CocoaPods, I encoutnered the following git issue. I even tried to create a new project to test already, but still see the same error. Do you mind to advise? 

**Podfile:** 
platform :ios, '9.0'

target 'OGenKi' do
  use_frameworks!

  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'SVProgressHUD'
  pod 'Firebase/Core'
  pod 'Clarifai-Apple-SDK', '3.0.0-beta8'

  target 'OGenKiTests' do
    inherit! :search_paths
  end

  target 'OGenKiUITests' do
    inherit! :search_paths
  end

end

**Error that I encountered during pod install:** 

Installing Clarifai-Apple-SDK (3.0.0-beta8)

[!] Error installing Clarifai-Apple-SDK
[!] /usr/bin/git clone https://github.com/Clarifai/clarifai-apple-sdk.git /var/folders/fz/pxkgsp6j3d946l3f71v3sj_00000gn/T/d20171007-1253-2o4o4n --template= --single-branch --depth 1 --branch 3.0.0-beta8

Cloning into '/var/folders/fz/pxkgsp6j3d946l3f71v3sj_00000gn/T/d20171007-1253-2o4o4n'...
Note: checking out '925e5de908aaf42a95756ec5611a078fd54c42de'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

git-lfs filter-process: git-lfs: command not found
fatal: The remote end hung up unexpectedly
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by heng2j** [comment]
And when I use the Manual installation instruction, I received the linker issue. Can you advise? 



ld: framework not found Clarifai_Apple_SDK
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by dcirne** [comment]
Hi @heng2j,

Can we go through a checklist to verify you have everything needed to install the SDK?

- [ ] Do you have Git-LFS installed on your machine? If not, you can find the installation instructions at [https://git-lfs.github.com](https://git-lfs.github.com). Git LFS is required for both CocoaPods and manual installations
- [ ] CocoaPods version? We are using CocoaPods 1.3.1. If you need upgrading, you can do so by running `sudo gem install cocoapods`
- [ ] Upgraded local CocoaPods repository. You may need to force upgrade your local, cached, repository with: `pod install --repo-update`

**Comment by heng2j** [comment]
Hi @dcirne,

Thank you so much to clarified the requirements. I did try pod install --repo-update, and I am already using CocoaPods 1.3.1. However, I didn't have Git-LFS installed. And now it works! And I am able to install Clarifai_Apple_SDK! Appreciated!
