### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by peterwarbo** [Clarifai/clarifai-apple-sdk#7]
I'm using the pod.

What seems to be the problem officer?

> ld: warning: ignoring file /xxx/Pods/Clarifai-Apple-SDK/Clarifai_Apple_SDK.framework/Clarifai_Apple_SDK, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (x86_64): /xxx/Pods/Clarifai-Apple-SDK/Clarifai_Apple_SDK.framework/Clarifai_Apple_SDK
> Undefined symbols for architecture x86_64:
>   "_OBJC_CLASS_$_Clarifai", referenced from:
>       objc-class-ref in ClarifaiUtil.o
>   "_CAIModelDidBecomeAvailableNotification", referenced from:
>       __T09TagBrdKit12ClarifaiUtilCACycfc in ClarifaiUtil.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by dcirne** [comment]
Hi @peterwarbo,

Can we go through a checklist to verify you have everything needed to install the SDK?

- [ ] Do you have Git-LFS installed on your machine? If not, you can find the installation instructions at [https://git-lfs.github.com](https://git-lfs.github.com). Git LFS is required for both CocoaPods and manual installations
- [ ] CocoaPods version? We are using CocoaPods 1.3.1. If you need upgrading, you can do so by running `sudo gem install cocoapods`
- [ ] Upgraded local CocoaPods repository. You may need to force upgrade your local, cached, repository with: `pod install --repo-update`

**Comment by peterwarbo** [comment]
Hi @dcirne 

Thanks I've just now done that. Maybe you should add that information to the README? :)

**Comment by dcirne** [comment]
Thanks @peterwarbo. The information was in the [README](https://github.com/Clarifai/clarifai-apple-sdk#git-lfs).

**Comment by cashmash** [comment]
**[Unable to compile]**

I have done all this: https://github.com/Clarifai/clarifai-apple-sdk/issues/7#issuecomment-336637296, but still unable to compile.

- System: 
  - XCode 10.1
  - macOS Mojave Version 10.14 
  - iOS 12.1
- Pod:
  - `pod 'Clarifai-Apple-SDK', '3.0.0-beta24'` 

```
ld: warning: ignoring file PROJECT_PATH/Pods/Clarifai-Apple-SDK/Clarifai_Apple_SDK.framework/Clarifai_Apple_SDK, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (arm64): PROJECT_PATH/Pods/Clarifai-Apple-SDK/Clarifai_Apple_SDK.framework/Clarifai_Apple_SDK
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_CAIOutput", referenced from:
      objc-class-ref in App.o
  "_OBJC_CLASS_$_CAIImage", referenced from:
      objc-class-ref in App.o
  "_OBJC_CLASS_$_CAIInput", referenced from:
      objc-class-ref in App.o
  "_OBJC_CLASS_$_CAIDataAsset", referenced from:
      objc-class-ref in App.o
  "_OBJC_CLASS_$_Clarifai", referenced from:
      objc-class-ref in App.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
