### ISSUE TITLE
Models other than general?

### ISSUE THREAD

**Issue by peterwarbo** [Clarifai/clarifai-apple-sdk#8]
How can I obtain models other than general?

`Clarifai.sharedInstance().generalModel` seems to be the only Model listed?

**Comment by dcirne** [comment]
Currently other models are not yet supported. This feature will be added in future releases of the SDK.

**Comment by peterwarbo** [comment]
What would you say is the timeline for incorporating other models in the SDK?

**Comment by dcirne** [comment]
Stay tuned, new features are always been released on a regular basis. When released, other models will be listed on the release notes and changelog.

**Comment by crabman448** [comment]
Any updates on this issue?
