### ISSUE TITLE
Cannot run on device

### ISSUE THREAD

**Issue by somedev** [Clarifai/clarifai-apple-sdk#9]
I know that this is duplicate of #5 and #3 (partly), but there's no solution found to fix this problem. 
My setup is: manual framework installation, manual code signing in Xcode, framework version: 3.0.0-beta8. Issue reproduces if I'm installing framework via Cocoapods.
Works fine on the simulator, but when I'm trying to run on real device it fails with error: "App Installation Failed. This application’s bundle identifier does not match its code signing identifier."
I've made some research and found 2 options to fix this issue in my project:
1. Use *Automatically manage signing* option in Xcode. In that case everything works as expected: I can run my app with library integrated on the simulator and on the device. But this option doesn't fit my needs, because I'm using fastlane match to manage code signing.
2. Remove simulator support from framework. The original idea is from this article: http://ikennd.ac/blog/2015/02/stripping-unwanted-architectures-from-dynamic-libraries-in-xcode/. Modifying framework:
```
lipo -remove x86_64 Clarifai_Apple_SDK.framework/Clarifai_Apple_SDK -output Clarifai_Apple_SDK.framework/Clarifai_Apple_SDK
lipo -remove i386 Clarifai_Apple_SDK.framework/Clarifai_Apple_SDK -output Clarifai_Apple_SDK.framework/Clarifai_Apple_SDK
```
Using modified framework I can run on device when manual code signing is used. And of course can't run on the simulator. So, it works, but looks like not a clear solution. By the way, I don't have such problems with other frameworks (ex. Fabric.framework) in my project.

Any thoughts?

**Comment by dcirne** [comment]
Hi @somedev,

The SDK does not require or uses any way, shape, or form of signing. And there should be no need to surgically remove any architecture from the SDK, since the compiler does this job when generating an app to a destination (i.e. simulator, device.)

It is hard to diagnose something without the Xcode project itself, but we can try a few things.

1. Did you have Git-LFS installed prior to cloning the SDK repository from GitHub? If not, then you would probably need to re-clone it after installation.

2. Have you tried using the SDK on a new project, without any other frameworks?

**Comment by somedev** [comment]
Hi @dcirne,
Thanks for your answer. I know that code signing is related to project, not a framework. And I have no clue why it works fine when simulator builds removed from framework. 

Answering to your questions:
1. Yep, I have  Git-LFS installed. My Clarifai_Apple_SDK.framework file size is ~ 222MB
2. Yes, I've made empty project with just Clarifai_Apple_SDK.framework integrated (manually). The issue is still here.

I've checked also Xcode 8.3: the issue reproduces as well.

**Comment by dcirne** [comment]
@somedev today we released a new version of the SDK, including new instructions for the [Manual Installation](https://github.com/Clarifai/clarifai-apple-sdk#manual-installation). The new process includes a **Build Phase** running a script.

This addresses your case, and now you should be able to run on devices and in the simulator.

**Comment by somedev** [comment]
@dcirne now it works fine on both: simulator and device. 
Thank you 👍
